### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by grotos** [JalfResi/GoTidy#5]
Could you give some installation instruction for Windows? Using simple go get results in error:

```
fatal error: tidy.h: No such file or directory compilation terminated.
```

**Comment by JalfResi** [comment]
Sorry, this package uses cgo to link to the libtidy library. I have no idea if that is even possible under Windows! I work on UNIX platforms predominantly.

However, if it is possible to get working I would gladly accept pull requests!
